version: "3.8"
services:
  back:
    build: ./back
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./back:/app
      - ./app/node_modules
  front:
    build: ./front
    container_name: myblog_c
    ports:
      - '3000:3000'
    volumes:
      - ./front:/app
      - ./app/node_modules  
    